root_path: /mnt/c/Users/joberlin/OneDrive - US House of Representatives/Sprints/analytics
sprints_xl_filepath: /mnt/c/Users/joberlin/OneDrive - US House of Representatives/Sprints/Sprints.xlsx
digest_path: /mnt/c/Users/joberlin/OneDrive - US House of Representatives/Sprints/Reports

